### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by masrufjaman** [masrufjaman/gas-n-go#1]
Please add Database Schema on Wiki.

**Comment by Anandah1813264642** [comment]
Yes, I added Database schema file on Wiki. 
Follow the link given below:
https://github.com/masrufjaman/gas-n-go/wiki/DATABASE-SCHEMA

**Comment by masrufjaman** [comment]
Please upload the ER diagram.

**Comment by anandahrafi** [comment]
I uploaded the ER diagram. Here is the link address:  https://github.com/masrufjaman/gas-n-go/wiki/DATABASE-SCHEMA#er-diagram
