### ISSUE TITLE
Chnage Text

### ISSUE THREAD

**Issue by masrufjaman** [masrufjaman/gas-n-go#16]
I've found these lines for a change. And I commented on them. Please edit these lines.

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by anandahrafi** [comment]
[a9ab6082240128ce57bf31eb9c04a91ca1daf169](https://github.com/masrufjaman/gas-n-go/commit/a9ab6082240128ce57bf31eb9c04a91ca1daf169)

I have changed some text of our web.
