### ISSUE TITLE
About Us page Not working

### ISSUE THREAD

**Issue by masrufjaman** [masrufjaman/gas-n-go#9]
Your commit [535b441fd423e3bdee25b2f1b1ef66bc5a39c8f9](https://github.com/masrufjaman/gas-n-go/commit/535b441fd423e3bdee25b2f1b1ef66bc5a39c8f9). This is not working properly. Please, fix this problem as soon as possible.

**Comment by anandahrafi** [comment]
[3f51a9990493dce179d069f60c127ab57c2abf8e](https://github.com/masrufjaman/gas-n-go/commit/3f51a9990493dce179d069f60c127ab57c2abf8e)

It has been solved by the commit

**Comment by masrufjaman** [comment]
**Great**.
